"""
KiCad Parser - Python Library for Parsing KiCad Files

A comprehensive Python library for parsing and manipulating KiCad S-Expression files,
including symbol libraries (.kicad_sym) and footprints (.kicad_mod).

Main Classes:
- KiCadSymbolLibrary: Symbol library container
- KiCadSymbol: Individual symbol definition
- KiCadFootprint: Footprint definition
- Position, Stroke, Fill, TextEffects: Common data structures

Main Functions:
- load_kicad_file: Load any KiCad file with auto-detection
- save_kicad_file: Save KiCad objects to files
- detect_file_type: Detect KiCad file type from content
"""

__version__ = "1.0.0"
__author__ = "Steffen-W"
__email__ = "your.email@example.com"

from .file_comparison_utils import (
    KiCadFileType,
    detect_kicad_file_type,
)
from .kicad_board import (
    DrillDefinition,
    Footprint3DModel,
    FootprintArc,
    FootprintAttributes,
    FootprintCircle,
    FootprintLine,
    FootprintPad,
    FootprintPolygon,
    FootprintRectangle,
    FootprintText,
    FootprintTextType,
    FootprintType,
    KiCadFootprint,
    Net,
    PadShape,
    PadType,
)
from .kicad_board_elements import (
    PadConnection,
    Zone,
    ZoneConnect,
    ZoneFillSettings,
    parse_zone_connect,
)
from .kicad_common import (
    UUID,
    CoordinatePoint,
    CoordinatePointList,
    Fill,
    FillType,
    Font,
    Image,
    KiCadObject,
    PageSettings,
    Position,
    Property,
    Stroke,
    StrokeType,
    TextEffects,
    TitleBlock,
    sexpr_to_str,
    str_to_sexpr,
)
from .kicad_design_rules import (
    ConstraintType,
    ConstraintValue,
    DesignRule,
    DesignRuleConstraint,
    DisallowType,
    DRCSeverity,
    KiCadDesignRules,
    create_basic_design_rules,
    load_design_rules,
    parse_kicad_design_rules_file,
    save_design_rules,
    write_kicad_design_rules_file,
)
from .kicad_file import (
    convert_file,
    detect_file_type,
    detect_file_type_from_path,
    load_footprint,
    load_kicad_file,
    load_symbol_library,
    load_worksheet,
    parse_kicad_file,
    save_footprint,
    save_kicad_file,
    save_symbol_library,
    save_worksheet,
    serialize_kicad_object,
    validate_kicad_file,
)
from .kicad_graphics import (
    Dimension,
    DimensionFormat,
    DimensionStyle,
    DimensionType,
    GraphicalArc,
    GraphicalBezier,
    GraphicalCircle,
    GraphicalLine,
    GraphicalPolygon,
    GraphicalRectangle,
    GraphicalText,
    GraphicalTextBox,
)
from .kicad_main import (
    create_basic_footprint,
    create_basic_symbol,
    create_basic_worksheet,
    example_footprint_creation,
    example_symbol_creation,
    load_any_kicad_file,
    parse_any_kicad_file,
    save_any_kicad_file,
)
from .kicad_pcb import (
    BoardLayer,
    BoardNet,
    BoardSetup,
    GeneralSettings,
    KiCadPCB,
    LayerType,
    TrackArc,
    TrackSegment,
    TrackVia,
    ViaType,
    create_basic_pcb,
    load_pcb,
    save_pcb,
)
from .kicad_schematic import (
    Bus,
    BusEntry,
    GlobalLabel,
    HierarchicalLabel,
    HierarchicalPin,
    HierarchicalSheet,
    Junction,
    KiCadSchematic,
    LabelShape,
    LocalLabel,
    NoConnect,
    Polyline,
    RootSheetInstance,
    SchematicSymbol,
    SchematicText,
    SheetInstance,
    SheetProject,
    SymbolInstance,
    SymbolProject,
    Wire,
    create_basic_schematic,
    load_schematic,
    save_schematic,
)
from .kicad_symbol import (
    KiCadSymbol,
    KiCadSymbolLibrary,
    PinElectricalType,
    PinGraphicStyle,
    SymbolArc,
    SymbolBezier,
    SymbolCircle,
    SymbolPin,
    SymbolPolyline,
    SymbolProperty,
    SymbolRectangle,
    SymbolText,
    SymbolUnit,
)
from .kicad_worksheet import (
    CornerType,
    KiCadWorksheet,
    WorksheetBitmap,
    WorksheetLine,
    WorksheetPolygon,
    WorksheetRectangle,
    WorksheetSetup,
    WorksheetText,
)

# Define what gets imported with "from kicad_parser import *"
__all__ = [
    # Version info
    "__version__",
    # File comparison utilities
    "KiCadFileType",
    "detect_kicad_file_type",
    # Common classes
    "KiCadObject",
    "Position",
    "CoordinatePoint",
    "CoordinatePointList",
    "Stroke",
    "StrokeType",
    "Fill",
    "FillType",
    "TextEffects",
    "UUID",
    "Property",
    "Font",
    "PageSettings",
    "TitleBlock",
    "Image",
    "str_to_sexpr",
    "sexpr_to_str",
    # Symbol classes
    "KiCadSymbolLibrary",
    "KiCadSymbol",
    "SymbolUnit",
    "SymbolProperty",
    "SymbolPin",
    "SymbolArc",
    "SymbolCircle",
    "SymbolRectangle",
    "SymbolText",
    "SymbolPolyline",
    "SymbolBezier",
    "PinElectricalType",
    "PinGraphicStyle",
    # Board/Footprint classes
    "KiCadFootprint",
    "FootprintText",
    "FootprintLine",
    "FootprintRectangle",
    "FootprintCircle",
    "FootprintArc",
    "FootprintPolygon",
    "FootprintPad",
    "Footprint3DModel",
    "Net",
    "FootprintAttributes",
    "DrillDefinition",
    "PadType",
    "PadShape",
    "FootprintType",
    "FootprintTextType",
    # Board Element classes
    "Zone",
    "ZoneConnect",
    "ZoneFillSettings",
    "PadConnection",
    "parse_zone_connect",
    # Graphics classes
    "GraphicalText",
    "GraphicalLine",
    "GraphicalRectangle",
    "GraphicalCircle",
    "GraphicalArc",
    "GraphicalPolygon",
    "GraphicalBezier",
    "GraphicalTextBox",
    "Dimension",
    "DimensionFormat",
    "DimensionStyle",
    "DimensionType",
    # File I/O functions
    "load_kicad_file",
    "save_kicad_file",
    "load_symbol_library",
    "save_symbol_library",
    "load_footprint",
    "save_footprint",
    "load_worksheet",
    "save_worksheet",
    # Parsing functions
    "parse_kicad_file",
    "serialize_kicad_object",
    # Utility functions
    "detect_file_type",
    "detect_file_type_from_path",
    "convert_file",
    "validate_kicad_file",
    "detect_kicad_file_type",
    "parse_any_kicad_file",
    "load_any_kicad_file",
    "save_any_kicad_file",
    "create_basic_symbol",
    "create_basic_footprint",
    "create_basic_worksheet",
    "example_symbol_creation",
    "example_footprint_creation",
    # Worksheet classes
    "KiCadWorksheet",
    "WorksheetSetup",
    "WorksheetLine",
    "WorksheetRectangle",
    "WorksheetPolygon",
    "WorksheetText",
    "WorksheetBitmap",
    "CornerType",
    # Schematic classes
    "KiCadSchematic",
    "Junction",
    "NoConnect",
    "BusEntry",
    "Wire",
    "Bus",
    "Polyline",
    "SchematicText",
    "LocalLabel",
    "GlobalLabel",
    "HierarchicalLabel",
    "SchematicSymbol",
    "HierarchicalSheet",
    "HierarchicalPin",
    "RootSheetInstance",
    "SymbolInstance",
    "SymbolProject",
    "SheetInstance",
    "SheetProject",
    "LabelShape",
    # Schematic functions
    "load_schematic",
    "save_schematic",
    "create_basic_schematic",
    # PCB classes
    "KiCadPCB",
    "GeneralSettings",
    "BoardLayer",
    "BoardSetup",
    "BoardNet",
    "TrackSegment",
    "TrackVia",
    "TrackArc",
    "LayerType",
    "ViaType",
    # PCB functions
    "load_pcb",
    "save_pcb",
    "create_basic_pcb",
    # Design Rules classes
    "KiCadDesignRules",
    "DesignRule",
    "DesignRuleConstraint",
    "ConstraintValue",
    "ConstraintType",
    "DisallowType",
    "DRCSeverity",
    # Design Rules functions
    "load_design_rules",
    "save_design_rules",
    "parse_kicad_design_rules_file",
    "write_kicad_design_rules_file",
    "create_basic_design_rules",
]
