"""KiCad Parser v2 - Complete S-expression token classes.

This module provides a comprehensive set of dataclasses representing all KiCad
S-expression tokens. Each class corresponds exactly to one S-expression token
and follows a consistent structure for parsing and serialization.

The classes are organized into logical modules based on dependencies:
- base_element: Base KiCadObject class
- enums: Common enumeration types for type safety
- base_types: Fundamental types with no dependencies (37 classes)
- text_and_documents: Text and document elements (27 classes)
- pad_and_drill: Pad and drill elements (17 classes)
- primitive_graphics: Basic graphics primitives (8 classes)
- advanced_graphics: Complex graphics objects (20 classes)
- symbol_library: Symbol management (15 classes)
- footprint_library: Footprint management (12 classes)
- zone_system: Zone and copper filling (28 classes)
- board_layout: PCB board design (14 classes)
- schematic_system: Schematic drawing (13 classes)

Total: 207 classes representing all KiCad S-expression tokens.

Usage:
    from kicad_parserv2 import At, Layer, Footprint

    # Create objects using dataclass syntax
    position = At(x=10.0, y=20.0, angle=90.0)
    layer = Layer(name="F.Cu")
    footprint = Footprint(library_link="Resistor_SMD:R_0603", layer="F.Cu")
"""

# Advanced graphics (20 classes) - complex graphics with dependencies: base_types, text_and_documents
from .advanced_graphics import (
    Dimension,
    Format,
    FpArc,
    FpCircle,
    FpCurve,
    FpLine,
    FpPoly,
    FpRect,
    FpText,
    FpTextBox,
    GrArc,
    GrBbox,
    GrCircle,
    GrText,
    GrTextBox,
    LeaderLength,
    OverrideValue,
    Precision,
    RenderCache,
    SuppressZeros,
    UnitsFormat,
)

# Base element
from .base_element import KiCadObject
from .base_element import ParseStrictness
from .base_element import ParseStrictness as ParseMode

# Base types (36 classes) - fundamental types with no cross-dependencies
from .base_types import (
    Anchor,
    Angle,
    At,
    Center,
    Clearance,
    Color,
    Diameter,
    Effects,
    End,
    Fill,
    Font,
    Height,
    Id,
    Justify,
    Layer,
    Linewidth,
    Locked,
    Name,
    Offset,
    Pos,
    Property,
    Pts,
    Radius,
    Rotate,
    Size,
    Start,
    Stroke,
    Style,
    Text,
    Thickness,
    Title,
    Tstamp,
    Type,
    Units,
    Uuid,
    Visible,
    Width,
    Xy,
    Xyz,
)

# Board layout (15 classes) - dependencies: base_types
from .board_layout import (
    General,
    Layers,
    NetName,
    Nets,
    Orientation,
    Path,
    PrivateLayers,
    Segment,
    Setup,
    Tracks,
    Via,
    Vias,
    ViaSize,
)

# Enums - common enumeration types for type safety
from .enums import (
    ClearanceType,
    FillType,
    FootprintTextType,
    HatchStyle,
    JustifyHorizontal,
    JustifyVertical,
    LabelShape,
    LayerType,
    PadShape,
    PadType,
    PinElectricalType,
    PinGraphicStyle,
    SmoothingStyle,
    StrokeType,
    ViaType,
    ZoneConnection,
    ZoneFillMode,
    ZoneKeepoutSetting,
)

# Footprint library (12 classes) - dependencies: base_types, symbol_library, pad_and_drill
from .footprint_library import (
    Attr,
    AutoplaceCost90,
    AutoplaceCost180,
    Footprint,
    Footprints,
    Model,
    NetTiePadGroups,
    OnBoard,
    SolderMaskMargin,
    SolderPasteMargin,
    SolderPasteMarginRatio,
    Tags,
)

# Pad and drill elements (18 classes) - dependencies: base_types
from .pad_and_drill import (
    Chamfer,
    ChamferRatio,
    DieLength,
    Drill,
    Free,
    Net,
    Options,
    Pad,
    Pads,
    Primitives,
    RoundrectRratio,
    Shape,
    SolderPasteRatio,
    ThermalBridgeWidth,
    ThermalGap,
    ThermalWidth,
    ZoneConnect,
)

# Primitive graphics (8 classes) - basic geometric primitives - dependencies: base_types
from .primitive_graphics import (
    Arc,
    Bezier,
    Circle,
    Line,
    Polygon,
    Polyline,
    Rect,
    Rectangle,
)

# Schematic system (13 classes) - dependencies: base_types, symbol_library
from .schematic_system import (
    Bus,
    BusEntry,
    GlobalLabel,
    Incrx,
    Incry,
    Junction,
    Label,
    Length,
    NoConnect,
    Project,
    Repeat,
    Sheet,
    Wire,
)

# S-Expression Parser
from .sexpr_parser import (
    SExpr,
    SExprParser,
    SExprValue,
    parse_sexpr,
    sexpr_to_str,
    str_to_sexpr,
)

# Symbol library (15 classes) - dependencies: base_types
from .symbol_library import (
    Extends,
    FieldsAutoplaced,
    InBom,
    Instances,
    LibSymbols,
    Number,
    Pin,
    Pinfunction,
    PinNames,
    PinNumbers,
    Pintype,
    Prefix,
    Symbol,
    UnitName,
)

# Text and document elements (27 classes) - dependencies: base_types
from .text_and_documents import (
    Bitmap,
    BottomMargin,
    Comment,
    Company,
    Data,
    Date,
    Descr,
    Generator,
    Group,
    Image,
    KicadWks,
    LeftMargin,
    Members,
    Page,
    Paper,
    Pngdata,
    Rev,
    RightMargin,
    Scale,
    Suffix,
    Tbtext,
    Tedit,
    Textlinewidth,
    Textsize,
    TitleBlock,
    TopMargin,
    Version,
)

# Zone system (28 classes) - zone definition and filling - dependencies: base_types, primitive_graphics
from .zone_system import (
    ConnectPads,
    Copperpour,
    EpsilonR,
    FilledAreasThickness,
    FilledPolygon,
    FilledSegments,
    FillSegments,
    Hatch,
    HatchBorderAlgorithm,
    HatchGap,
    HatchMinHoleArea,
    HatchOrientation,
    HatchSmoothingLevel,
    HatchSmoothingValue,
    HatchThickness,
    IslandAreaMin,
    IslandRemovalMode,
    KeepEndLayers,
    Keepout,
    LossTangent,
    Material,
    MinThickness,
    Mode,
    Priority,
    RemoveUnusedLayer,
    RemoveUnusedLayers,
    Smoothing,
    Zone,
)

__all__ = [
    # Base
    "KiCadObject",
    "ParseMode",
    "ParseStrictness",
    # S-Expression Parser
    "SExprParser",
    "SExpr",
    "SExprValue",
    "parse_sexpr",
    "str_to_sexpr",
    "sexpr_to_str",
    # Enums
    "ClearanceType",
    "FillType",
    "FootprintTextType",
    "HatchStyle",
    "JustifyHorizontal",
    "JustifyVertical",
    "LabelShape",
    "LayerType",
    "PadShape",
    "PadType",
    "PinElectricalType",
    "PinGraphicStyle",
    "SmoothingStyle",
    "StrokeType",
    "ViaType",
    "ZoneConnection",
    "ZoneFillMode",
    "ZoneKeepoutSetting",
    # Base types (37)
    "Anchor",
    "Angle",
    "At",
    "Center",
    "Clearance",
    "Color",
    "Diameter",
    "Effects",
    "End",
    "Fill",
    "Font",
    "Height",
    "Id",
    "Justify",
    "Layer",
    "Linewidth",
    "Locked",
    "Name",
    "Offset",
    "Pos",
    "Property",
    "Pts",
    "Radius",
    "Rotate",
    "Size",
    "Start",
    "Stroke",
    "Style",
    "Text",
    "Thickness",
    "Title",
    "Tstamp",
    "Type",
    "Units",
    "Uuid",
    "Visible",
    "Width",
    "Xy",
    "Xyz",
    # Text and documents (27)
    "Bitmap",
    "BottomMargin",
    "Comment",
    "Company",
    "Data",
    "Date",
    "Descr",
    "Generator",
    "Group",
    "Image",
    "KicadWks",
    "LeftMargin",
    "Members",
    "Page",
    "Paper",
    "Pngdata",
    "Rev",
    "RightMargin",
    "Scale",
    "Suffix",
    "Tbtext",
    "Tedit",
    "Textlinewidth",
    "Textsize",
    "TitleBlock",
    "TopMargin",
    "Version",
    # Pad and drill (18)
    "Chamfer",
    "ChamferRatio",
    "DieLength",
    "Drill",
    "Free",
    "Net",
    "Options",
    "Clearance",
    "Pad",
    "Pads",
    "Primitives",
    "RoundrectRratio",
    "Shape",
    "SolderPasteRatio",
    "ThermalBridgeWidth",
    "ThermalGap",
    "ThermalWidth",
    "ZoneConnect",
    # Primitive graphics (8)
    "Arc",
    "Bezier",
    "Circle",
    "Line",
    "Polygon",
    "Polyline",
    "Rect",
    "Rectangle",
    # Advanced graphics (20)
    "Dimension",
    "Format",
    "FpArc",
    "FpCircle",
    "FpCurve",
    "FpLine",
    "FpPoly",
    "FpRect",
    "FpText",
    "FpTextBox",
    "GrArc",
    "GrBbox",
    "GrCircle",
    "GrText",
    "GrTextBox",
    "LeaderLength",
    "Precision",
    "RenderCache",
    "SuppressZeros",
    "UnitsFormat",
    # Symbol library (15)
    "Extends",
    "FieldsAutoplaced",
    "InBom",
    "Instances",
    "LibSymbols",
    "Number",
    "Pin",
    "Pinfunction",
    "PinNames",
    "PinNumbers",
    "Pintype",
    "Prefix",
    "Symbol",
    "UnitName",
    # Footprint library (12)
    "Attr",
    "AutoplaceCost180",
    "AutoplaceCost90",
    "Footprint",
    "Footprints",
    "Model",
    "NetTiePadGroups",
    "OnBoard",
    "SolderMaskMargin",
    "SolderPasteMargin",
    "SolderPasteMarginRatio",
    "Tags",
    # Zone system (28)
    "ConnectPads",
    "Copperpour",
    "EpsilonR",
    "FillSegments",
    "FilledAreasThickness",
    "FilledPolygon",
    "FilledSegments",
    "Hatch",
    "HatchBorderAlgorithm",
    "HatchGap",
    "HatchMinHoleArea",
    "HatchOrientation",
    "HatchSmoothingLevel",
    "HatchSmoothingValue",
    "HatchThickness",
    "IslandAreaMin",
    "IslandRemovalMode",
    "KeepEndLayers",
    "Keepout",
    "LossTangent",
    "Material",
    "MinThickness",
    "Mode",
    "Priority",
    "RemoveUnusedLayer",
    "RemoveUnusedLayers",
    "Smoothing",
    "Zone",
    # Board layout (14)
    "General",
    "Layers",
    "NetName",
    "Nets",
    "Orientation",
    "OverrideValue",
    "Path",
    "PrivateLayers",
    "Rotate",
    "Segment",
    "Setup",
    "Tracks",
    "Via",
    "ViaSize",
    "Vias",
    # Schematic system (13)
    "Bus",
    "BusEntry",
    "GlobalLabel",
    "Incrx",
    "Incry",
    "Junction",
    "Label",
    "Length",
    "NoConnect",
    "Project",
    "Repeat",
    "Sheet",
    "Wire",
]
